title: New York Benchmarking Project
description: Civic reform through benchmarking of New York State local governments.
theme: minima

author:
  name: New York Benchmarking Project

header_pages:
  - _pages/methods.md
  - _pages/about.md

plugins:
  - jekyll-feed
